/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_CMFormatDescription */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_CMFormatDescription
#define _Included_org_jitsi_impl_neomedia_avfoundation_CMFormatDescription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_CMFormatDescription
 * Method:    sizeForKey
 * Signature: (JLjava/lang/String;)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_org_jitsi_impl_neomedia_avfoundation_CMFormatDescription_sizeForKey
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
