/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_AVCaptureSession */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
#define _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
 * Method:    addInput
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession_addInput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
 * Method:    addOutput
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession_addOutput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
 * Method:    allocAndInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession_allocAndInit
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
 * Method:    startRunning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession_startRunning
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureSession
 * Method:    stopRunning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureSession_stopRunning
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
