/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer
#define _Included_org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer
 * Method:    bytesForAllSamples
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer_bytesForAllSamples
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer
 * Method:    formatDescription
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_avfoundation_CMSampleBuffer_formatDescription
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
