/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_AVCaptureDeviceInput */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureDeviceInput
#define _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureDeviceInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDeviceInput
 * Method:    deviceInputWithDevice
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDeviceInput_deviceInputWithDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
