/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
#define _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    allocAndInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_allocAndInit
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    videoMinFrameDuration
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_videoMinFrameDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    pixelBufferAttributes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_pixelBufferAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    setAlwaysDiscardsLateVideoFrames
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_setAlwaysDiscardsLateVideoFrames
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    setDelegate
 * Signature: (JLorg/jitsi/impl/neomedia/avfoundation/AVCaptureVideoDataOutput/Delegate;)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_setDelegate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    setVideoMinFrameDuration
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_setVideoMinFrameDuration
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput
 * Method:    setPixelBufferAttributes
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureVideoDataOutput_setPixelBufferAttributes
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
