/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice */

#ifndef _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
#define _Included_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    formatDescriptions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_formatDescriptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    inputDevicesWithMediaType
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_inputDevicesWithMediaType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    isConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_isConnected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    localizedName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_localizedName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    open
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice
 * Method:    uniqueID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jitsi_impl_neomedia_avfoundation_AVCaptureDevice_uniqueID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
